import { FlexContainerProperties, FlexItemProperties, FlexDirection, FlexWrap, FlexJustifyContent, FlexAlignItems, FlexAlignContent, FlexComponent } from './flex-container/component';
import { AbstractApp } from './abstract-app';
import { AccordionType, AccordionComponent } from './accordion/component';
import { BoxComponent } from './box/component';
import { WizardStep, NidocaWizard } from './wizard/component';
import { ChipComponent } from './chip/component';
import { ProgressType, ProgressComponent } from './progress/component';
import { ShadowType, BorderProperties, BorderSize, BorderComponent } from './border/component';
import { FloatingComponent } from './floating/component';
import { AccordionItemComponent } from './accordion/item/component';
import { ButtonType, ButtonComponent } from './button/component';
import { CodeFormatter, CodeComponent } from './code/component';
import { DividerType, DividerComponent } from './divider/component';
import { GridAlignItems,GridJustifyItems, GridComponent } from './grid-container/component';
import { KeyValueData, FormComponentOutputData, FormComponent } from './form/component';
import { ContainerComponent } from './container/component';
import { RippleComponent } from './ripple/component';
import { VisibleType, VisibleEffect } from './visible/component';
import { TransitionType, TransitionComponent } from './effect-transition/component';
import { IconShadowType,IconComponent } from './icon/component';
import { RichMediaProperties, RichMediaType, RichMediaComponent } from './rich-media/component';
import { InputfieldType, InputfieldDataChangeEvent, InputfieldComponent } from './inputfield/component';
import { TargetType, LinkComponent } from './link/component';
import { ListComponent } from './list/component';
import { ListItemComponent } from './list/item/component';
import { TopAppBarComponent } from './top-app-bar/component';
import { NavigationType, NavigationComponent } from './navigation/component';
import { SearchBarState,SearchBarOutputData,SearchBarComponent } from './search-bar/component';
import { NavigationLinkComponent } from './navigation/navigation-link/component';
import { NavigationSectionComponent } from './navigation/navigation-section/component';
import { TableComponent } from './table/component';
import { SpacerAlignment, SpacerSize, SpacerComponent } from './spacer/component';
import { TabsComponent } from './tabs/component';
import { TabComponent } from './tabs/tab/component';
import { TabContentComponent } from './tabs/tab-content/component';
import { BasisTemplate } from './template-basis/component';
import { TopBottomTemplate } from './template-top-bottom-bars/component';
import { TypographyAlignment, TypographyType, TypographyComponent } from './typography/component';
import { DialogComponent } from './dialog/component';

export { FlexContainerProperties, FlexItemProperties, FlexDirection, FlexWrap, FlexJustifyContent, FlexAlignItems, FlexAlignContent, FlexComponent } from './flex-container/component';
export { AbstractApp } from './abstract-app';
export { AccordionType, AccordionComponent } from './accordion/component';
export { BoxComponent } from './box/component';
export { WizardStep, NidocaWizard } from './wizard/component';
export { ChipComponent } from './chip/component';
export { ProgressType, ProgressComponent } from './progress/component';
export { ShadowType, BorderProperties, BorderSize, BorderComponent } from './border/component';
export { FloatingComponent } from './floating/component';
export { AccordionItemComponent } from './accordion/item/component';
export { ButtonType, ButtonComponent } from './button/component';
export { CodeFormatter, CodeComponent } from './code/component';
export { DividerType, DividerComponent } from './divider/component';
export { GridAlignItems,GridJustifyItems, GridComponent } from './grid-container/component';
export { KeyValueData, FormComponentOutputData, FormComponent } from './form/component';
export { ContainerComponent } from './container/component';
export { RippleComponent } from './ripple/component';
export { VisibleType, VisibleEffect } from './visible/component';
export { TransitionType, TransitionComponent } from './effect-transition/component';
export { IconShadowType,IconComponent } from './icon/component';
export { RichMediaProperties, RichMediaType, RichMediaComponent } from './rich-media/component';
export { InputfieldType, InputfieldDataChangeEvent, InputfieldComponent } from './inputfield/component';
export { TargetType, LinkComponent } from './link/component';
export { ListComponent } from './list/component';
export { ListItemComponent } from './list/item/component';
export { TopAppBarComponent } from './top-app-bar/component';
export { NavigationType, NavigationComponent } from './navigation/component';
export { SearchBarState,SearchBarOutputData,SearchBarComponent } from './search-bar/component';
export { NavigationLinkComponent } from './navigation/navigation-link/component';
export { NavigationSectionComponent } from './navigation/navigation-section/component';
export { TableComponent } from './table/component';
export { SpacerAlignment, SpacerSize, SpacerComponent } from './spacer/component';
export { TabsComponent } from './tabs/component';
export { TabComponent } from './tabs/tab/component';
export { TabContentComponent } from './tabs/tab-content/component';
export { BasisTemplate } from './template-basis/component';
export { TopBottomTemplate } from './template-top-bottom-bars/component';
export { TypographyAlignment, TypographyType, TypographyComponent } from './typography/component';
export { DialogComponent } from './dialog/component';

//Auskommentieren bei erstellen neuer Version auf NPM, nach auskommentieren nochmal ts in js bauen
import './_showcase/showcase-app';
import './index.css';
