name: build pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run ts
      - run: npm run eslint
      - run: npm run lit-analyzer
      - run: npm run typedocs
      - run: npm run docs-webcomponents
      - run: npm run build:webcomponents
      - run: npm run build:app
      - run: npm run build:webcomponent-viewer
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_DOCUMENTATION_TOKEN }}
          branch: ${{ github.ref }}
          folder: public
          repository-name: domoskanonos/nidoca-documentation
          target-folder: /
          ssh-key: ${{ secrets.DEPLOY_DOCUMENTATION_TOKEN }}
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run ts
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
