name: build pipeline
on: [push]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/main') && (!contains(github.event.head_commit.message, '[RELEASE]')) }}
    steps:
      - uses: actions/checkout@v3
        #with:
          #token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build
      - run: git config --global user.name 'Dominik Bruhn'
      - run: git config --global user.email 'domoskanonos@googlemail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - run: npm run ts
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}