name: Publish to npm
on: [push]
  branches: [master]
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
